### ISSUE TITLE
Support OLS4 as terminology server

### ISSUE THREAD

**Issue by ChristophB** [Onto-Med/top-backend#173]
The current implementation only supports OLS3 which has been replace with OLS4 in October 2023.

Tests are failing, because we are using the official OLS4 instance as default setup!

**Comment by RalphBln** [comment]
Cannot reproduce. OLS4 has exactly the same API as OLS3. Tests complete without error on my end. Possibly a temporary outage of the official OLS instance.

Maybe we should fire up our own OLS instance at the test stage in order to be independent of the official one and prevent test failures due to outages or network disturbances that we cannot control. Will create another issue for this.
